# Generated by Django 3.1 on 2021-03-30 13:54

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('foot', 'foot'), ('bike', ' bike'), ('car', 'car')], max_length=4)),
                ('regions', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('hours', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=11), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(50)])),
                ('region', models.SmallIntegerField()),
                ('hours', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=11), size=None)),
                ('assign_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('complete_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('courier_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courier.courier')),
            ],
        ),
    ]
