# Generated by Django 3.1 on 2021-04-02 04:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courier',
            old_name='type',
            new_name='courier_type',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='hours',
            new_name='delivery_hours',
        ),
        migrations.RemoveField(
            model_name='courier',
            name='hours',
        ),
        migrations.AddField(
            model_name='courier',
            name='working_hours',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=11), blank=True, null=True, size=None),
        ),
    ]
